### ISSUE TITLE
Update the TextMate highlighting grammar for Tact

### ISSUE THREAD

**Issue by novusnota** [0xDmitry/hacktheton#24]
The currently used one [here](https://github.com/0xDmitry/hacktheton/blob/dev/packages/website/public/shiki/languages/grammar-tact.json) is an outdated grammar from either older versions of VS Code extension or Tact compiler sources.

I suggest to use the following one from the Tact docs (recently moved to compiler repo): https://github.com/tact-lang/tact/blob/main/docs/grammars/grammar-tact.json

It's kept up-to-date and is well-tested in the downstream repository, [tact-sublime](https://github.com/tact-lang/tact-sublime).

P.S.: Cool project!

**Comment by 0xDmitry** [comment]
Thx! Will take a look
